if (!Application.isPlaying) throw new System.Exception("Enter Play mode first.");
var game = Assets.Scripts.GameLogic.INSTANCE;
if (game == null) throw new System.Exception("Enter Game must load gameplay.");
int checks = 0;
System.Action<bool, string> require = (ok, message) => { checks++; if (!ok) throw new System.Exception(message); };
require(UnityEngine.SceneManagement.SceneManager.GetActiveScene().name == "In Game", "Correct gameplay scene.");
require(game.Loadout.PlacementElements.SequenceEqual(new[] { 100, 400 }) && game.Loadout.ReactionIds.SequenceEqual(Enumerable.Range(1000, 9)), "Gameplay received fire and stone only.");
require(game.Loadout.CanPlace(100) && game.Loadout.CanPlace(400) && !game.Loadout.CanPlace(200) && !game.Loadout.CanPlace(300), "Fundamental blocks determine placement.");
require(game.Loadout.GetReactions(100).Any(r => r.Effect == "Fire_Burnout"), "Fundamental fire includes decay.");
require(!game.Loadout.GetReactions(100).Any(r => r.Effect == "Fire_Water_Cardinal_Geyser"), "Unequipped cross reactions are absent.");
game.UpdateSelection(400); require(game.CurrentSelection == 400, "Equipped stone can be selected.");
game.UpdateSelection(200); require(game.CurrentSelection == 400, "Unequipped water cannot be selected.");
game.currMana = 100;
var player = Assets.Scripts.PlayerHandler.INSTANCE;
int row = player.r, col = player.c;
game.Board.Set(row, col, 0); game.MakeCastable();
require(game.CanQueueSpell(row, col, 100), "Equipped fire can queue on an open castable cell.");
require(!game.CanQueueSpell(row, col, 200) && !game.CanQueueSpell(row, col, 300), "Casting enforces permissions independently of UI.");
game.MakeMove(row, col, 200); require(!game.IsPlacementMode, "Direct MakeMove cannot bypass permissions.");
game.MakeMove(row, col, 100); require(game.IsPlacementMode, "Fire placement succeeds.");
game.RemoveQueuedSpell(row, col);
System.IO.File.WriteAllText("Temp/InventoryChecks/Gameplay.txt", "PASS: " + checks + " gameplay selection and casting assertions.");
return System.IO.File.ReadAllText("Temp/InventoryChecks/Gameplay.txt");
