if (!Application.isPlaying) throw new System.Exception("Run in the Inventory scene in Play mode.");
var controller = UnityEngine.Object.FindAnyObjectByType<Assets.Scripts.Inventory.InventoryController>();
if (controller == null || controller.State == null) throw new System.Exception("Inventory must be loaded.");
var state = controller.State;
int checks = 0;
System.Action<bool, string> require = (ok, message) => { checks++; if (!ok) throw new System.Exception(message); };
var flags = System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance;
string directory = "Temp/InventoryChecks/Runtime-" + System.Guid.NewGuid().ToString("N");
System.IO.Directory.CreateDirectory(directory);
var testStore = new Assets.Scripts.Inventory.InventorySaveStore(System.IO.Path.Combine(directory, "inventory.json"));
// Exercise production autosaving, but never write the player's actual save during validation.
typeof(Assets.Scripts.Inventory.InventorySession).GetField("store", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static).SetValue(null, testStore);
var mouse = UnityEngine.InputSystem.InputSystem.AddDevice<UnityEngine.InputSystem.Mouse>();
var eventSystem = UnityEngine.EventSystems.EventSystem.current;
bool eventsEnabled = eventSystem != null && eventSystem.enabled;
var settings = UnityEngine.InputSystem.InputSystem.settings;
var oldBackground = settings.backgroundBehavior;
var oldRouting = settings.editorInputBehaviorInPlayMode;
var update = typeof(Assets.Scripts.Inventory.InventoryController).GetMethod("Update", flags);
System.Action advance = () => typeof(UnityEngine.InputSystem.InputSystem).GetMethod("Update", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic, null, new[] { typeof(UnityEngine.InputSystem.LowLevel.InputUpdateType) }, null).Invoke(null, new object[] { UnityEngine.InputSystem.LowLevel.InputUpdateType.Dynamic });
System.Action<Assets.Scripts.Inventory.InventoryGridView, int, int, bool> pointer = (view, x, y, down) => {
    var world = view.background.GetCellCenterWorld(Assets.Scripts.Inventory.InventoryGridView.Cell(x, y));
    Vector2 screen = controller.viewCamera.WorldToScreenPoint(world);
    var picked = view.Pick(controller.viewCamera, screen);
    require(picked == new Vector2Int(x, y), "Tilemap cell picking matches display.");
    var input = new UnityEngine.InputSystem.LowLevel.MouseState { position = screen }.WithButton(UnityEngine.InputSystem.LowLevel.MouseButton.Left, down);
    UnityEngine.InputSystem.InputSystem.QueueStateEvent(mouse, input); advance(); update.Invoke(controller, null);
};
try {
    if (eventSystem != null) eventSystem.enabled = false;
    settings.backgroundBehavior = UnityEngine.InputSystem.InputSettings.BackgroundBehavior.IgnoreFocus;
    settings.editorInputBehaviorInPlayMode = UnityEngine.InputSystem.InputSettings.EditorInputBehaviorInPlayMode.AllDeviceInputAlwaysGoesToGameView;
    require(state.Items.Count == 6, "Starter inventory has six items.");
    var fire = state.Items.First(i => state.Definition(i).itemId == "fire");
    require(fire.grid == Assets.Scripts.Inventory.InventoryGrid.Storage, "Fresh profile starts in storage.");
    pointer(controller.storage, fire.x + 1, fire.y + 1, false);
    pointer(controller.storage, fire.x + 1, fire.y + 1, true);
    require(object.ReferenceEquals(controller.Dragging, fire), "Clicking the lower-right shape cell starts dragging its instance.");
    pointer(controller.active, 2, 2, true);
    var preview = controller.active.ghost;
    require(preview.GetTile(Assets.Scripts.Inventory.InventoryGridView.Cell(1, 1)) != null, "Preview retains grabbed-cell offset.");
    require(preview.GetTile(Assets.Scripts.Inventory.InventoryGridView.Cell(2, 1)) == null, "Preview leaves shape hole empty.");
    var color = preview.GetColor(Assets.Scripts.Inventory.InventoryGridView.Cell(1, 1));
    var itemColor = state.Definition(fire).color;
    require(Mathf.Approximately(color.a, .55f) && Mathf.Approximately(color.r, itemColor.r) &&
        Mathf.Approximately(color.g, itemColor.g) && Mathf.Approximately(color.b, itemColor.b),
        "Valid ghost keeps the item's color with preview transparency.");
    var image = CheckSupport.RenderCamera(controller.viewCamera, 1440, 900);
    System.IO.File.WriteAllBytes("Temp/InventoryChecks/ValidGhost.png", image.EncodeToPNG()); UnityEngine.Object.DestroyImmediate(image);
    pointer(controller.active, 2, 2, false);
    require(fire.grid == Assets.Scripts.Inventory.InventoryGrid.Active && fire.x == 1 && fire.y == 1, "Drop commits the preview origin.");
    require(controller.Dragging == null && preview.GetUsedTilesCount() == 0, "Drop clears dragging and ghost.");
    var saved = testStore.Load(() => throw new System.Exception("Expected save."), data => {}, out _);
    require(saved.items.Single(i => i.instanceId == fire.instanceId).grid == Assets.Scripts.Inventory.InventoryGrid.Active, "Transfer autosaves both grids.");
    pointer(controller.active, 1, 1, true);
    pointer(controller.active, 4, 4, true);
    color = preview.GetColor(Assets.Scripts.Inventory.InventoryGridView.Cell(4, 4));
    require(color.r > color.g && color.a < 1, "Invalid ghost is translucent red.");
    pointer(controller.active, 4, 4, false);
    require(fire.x == 1 && fire.y == 1 && controller.Dragging == null, "Invalid drop returns to original placement.");
    pointer(controller.active, 1, 1, true); controller.CancelDrag();
    require(fire.x == 1 && fire.y == 1 && controller.Dragging == null, "Cancellation preserves original placement.");
    pointer(controller.active, 1, 1, false);
    var stone = state.Items.First(i => state.Definition(i).itemId == "stone");
    require(state.Move(stone, Assets.Scripts.Inventory.InventoryGrid.Active, 0, 3), "Equip stone alongside fire.");
    require(state.BuildLoadout().PlacementElements.SequenceEqual(new[] { 100, 400 }) && state.BuildLoadout().ReactionIds.SequenceEqual(Enumerable.Range(1000, 9)), "Equipped reaction and placement grants only.");
    if (eventSystem != null) eventSystem.enabled = eventsEnabled;
    Canvas.ForceUpdateCanvases();
    var button = controller.enterButton;
    var hitPosition = controller.viewCamera.WorldToScreenPoint(button.transform.position);
    var eventData = new UnityEngine.EventSystems.PointerEventData(eventSystem) { position = hitPosition };
    var hits = new System.Collections.Generic.List<UnityEngine.EventSystems.RaycastResult>();
    eventSystem.RaycastAll(eventData, hits);
    require(hits.Any(h => h.gameObject == button.gameObject), "Enter Game button is reachable by the UI raycaster.");
    button.onClick.Invoke();
    require(Assets.Scripts.Inventory.InventorySession.CurrentRun.PlacementElements.SequenceEqual(new[] { 100, 400 }) && Assets.Scripts.Inventory.InventorySession.CurrentRun.ReactionIds.SequenceEqual(Enumerable.Range(1000, 9)), "Enter Game passes an explicit loadout snapshot.");
    System.IO.File.WriteAllText("Temp/InventoryChecks/Runtime.txt", "PASS: " + checks + " drag, ghost, autosave, UI, and handoff assertions.");
} finally {
    controller.CancelDrag();
    if (eventSystem != null) eventSystem.enabled = eventsEnabled;
    settings.backgroundBehavior = oldBackground; settings.editorInputBehaviorInPlayMode = oldRouting;
    UnityEngine.InputSystem.InputSystem.RemoveDevice(mouse);
}
return System.IO.File.ReadAllText("Temp/InventoryChecks/Runtime.txt");
